#include <stdio.h>
#include <ctype.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#define MAX_BUF 256
#define EMOJI_LIMIT 8192
#define VERSION "0.0.1"

// TODO: try converting the emojis list to a hashtable
// EMOJI ARRAY
int emojis_len = 1281;
char emojis[][MAX_BUF][MAX_BUF] = {
	{"copyright sign", "©"},
	{"registered sign", "®"},
	{"double exclamation mark", "‼"},
	{"exclamation question mark", "⁉"},
	{"trade mark sign", "™"},
	{"information source", "ℹ"},
	{"left right arrow", "↔"},
	{"up down arrow", "↕"},
	{"north west arrow", "↖"},
	{"north east arrow", "↗"},
	{"south east arrow", "↘"},
	{"south west arrow", "↙"},
	{"leftwards arrow with hook", "↩"},
	{"rightwards arrow with hook", "↪"},
	{"watch", "⌚"},
	{"hourglass", "⌛"},
	{"keyboard", "⌨"},
	{"eject symbol", "⏏"},
	{"black right-pointing double triangle", "⏩"},
	{"black left-pointing double triangle", "⏪"},
	{"black up-pointing double triangle", "⏫"},
	{"black down-pointing double triangle", "⏬"},
	{"black right-pointing double triangle with vertical bar", "⏭"},
	{"black left-pointing double triangle with vertical bar", "⏮"},
	{"black right-pointing triangle with double vertical bar", "⏯"},
	{"alarm clock", "⏰"},
	{"stopwatch", "⏱"},
	{"timer clock", "⏲"},
	{"hourglass with flowing sand", "⏳"},
	{"double vertical bar", "⏸"},
	{"black square for stop", "⏹"},
	{"black circle for record", "⏺"},
	{"circled latin capital letter m", "Ⓜ"},
	{"black small square", "▪"},
	{"white small square", "▫"},
	{"black right-pointing triangle", "▶"},
	{"black left-pointing triangle", "◀"},
	{"white medium square", "◻"},
	{"black medium square", "◼"},
	{"white medium small square", "◽"},
	{"black medium small square", "◾"},
	{"black sun with rays", "☀"},
	{"cloud", "☁"},
	{"umbrella", "☂"},
	{"snowman", "☃"},
	{"comet", "☄"},
	{"black telephone", "☎"},
	{"ballot box with check", "☑"},
	{"umbrella with rain drops", "☔"},
	{"hot beverage", "☕"},
	{"shamrock", "☘"},
	{"white up pointing index", "☝"},
	{"skull and crossbones", "☠"},
	{"radioactive sign", "☢"},
	{"biohazard sign", "☣"},
	{"orthodox cross", "☦"},
	{"star and crescent", "☪"},
	{"peace symbol", "☮"},
	{"yin yang", "☯"},
	{"wheel of dharma", "☸"},
	{"white frowning face", "☹"},
	{"white smiling face", "☺"},
	{"aries", "♈"},
	{"taurus", "♉"},
	{"gemini", "♊"},
	{"cancer", "♋"},
	{"leo", "♌"},
	{"virgo", "♍"},
	{"libra", "♎"},
	{"scorpius", "♏"},
	{"sagittarius", "♐"},
	{"capricorn", "♑"},
	{"aquarius", "♒"},
	{"pisces", "♓"},
	{"black spade suit", "♠"},
	{"black club suit", "♣"},
	{"black heart suit", "♥"},
	{"black diamond suit", "♦"},
	{"hot springs", "♨"},
	{"black universal recycling symbol", "♻"},
	{"wheelchair symbol", "♿"},
	{"hammer and pick", "⚒"},
	{"anchor", "⚓"},
	{"crossed swords", "⚔"},
	{"scales", "⚖"},
	{"alembic", "⚗"},
	{"gear", "⚙"},
	{"atom symbol", "⚛"},
	{"fleur-de-lis", "⚜"},
	{"warning sign", "⚠"},
	{"high voltage sign", "⚡"},
	{"medium white circle", "⚪"},
	{"medium black circle", "⚫"},
	{"coffin", "⚰"},
	{"funeral urn", "⚱"},
	{"soccer ball", "⚽"},
	{"baseball", "⚾"},
	{"snowman without snow", "⛄"},
	{"sun behind cloud", "⛅"},
	{"thunder cloud and rain", "⛈"},
	{"ophiuchus", "⛎"},
	{"pick", "⛏"},
	{"helmet with white cross", "⛑"},
	{"chains", "⛓"},
	{"no entry", "⛔"},
	{"shinto shrine", "⛩"},
	{"church", "⛪"},
	{"mountain", "⛰"},
	{"umbrella on ground", "⛱"},
	{"fountain", "⛲"},
	{"flag in hole", "⛳"},
	{"ferry", "⛴"},
	{"sailboat", "⛵"},
	{"skier", "⛷"},
	{"ice skate", "⛸"},
	{"person with ball", "⛹"},
	{"tent", "⛺"},
	{"fuel pump", "⛽"},
	{"black scissors", "✂"},
	{"white heavy check mark", "✅"},
	{"airplane", "✈"},
	{"envelope", "✉"},
	{"raised fist", "✊"},
	{"raised hand", "✋"},
	{"victory hand", "✌"},
	{"writing hand", "✍"},
	{"pencil", "✏"},
	{"black nib", "✒"},
	{"heavy check mark", "✔"},
	{"heavy multiplication x", "✖"},
	{"latin cross", "✝"},
	{"star of david", "✡"},
	{"sparkles", "✨"},
	{"eight spoked asterisk", "✳"},
	{"eight pointed black star", "✴"},
	{"snowflake", "❄"},
	{"sparkle", "❇"},
	{"cross mark", "❌"},
	{"negative squared cross mark", "❎"},
	{"black question mark ornament", "❓"},
	{"white question mark ornament", "❔"},
	{"white exclamation mark ornament", "❕"},
	{"heavy exclamation mark symbol", "❗"},
	{"heavy heart exclamation mark ornament", "❣"},
	{"heavy black heart", "❤"},
	{"heavy plus sign", "➕"},
	{"heavy minus sign", "➖"},
	{"heavy division sign", "➗"},
	{"black rightwards arrow", "➡"},
	{"curly loop", "➰"},
	{"double curly loop", "➿"},
	{"arrow pointing rightwards then curving upwards", "⤴"},
	{"arrow pointing rightwards then curving downwards", "⤵"},
	{"leftwards black arrow", "⬅"},
	{"upwards black arrow", "⬆"},
	{"downwards black arrow", "⬇"},
	{"black large square", "⬛"},
	{"white large square", "⬜"},
	{"white medium star", "⭐"},
	{"heavy large circle", "⭕"},
	{"wavy dash", "〰"},
	{"part alternation mark", "〽"},
	{"circled ideograph congratulation", "㊗"},
	{"circled ideograph secret", "㊙"},
	{"mahjong tile red dragon", "🀄"},
	{"playing card black joker", "🃏"},
	{"negative squared latin capital letter a", "🅰"},
	{"negative squared latin capital letter b", "🅱"},
	{"negative squared latin capital letter o", "🅾"},
	{"negative squared latin capital letter p", "🅿"},
	{"negative squared ab", "🆎"},
	{"squared cl", "🆑"},
	{"squared cool", "🆒"},
	{"squared free", "🆓"},
	{"squared id", "🆔"},
	{"squared new", "🆕"},
	{"squared ng", "🆖"},
	{"squared ok", "🆗"},
	{"squared sos", "🆘"},
	{"squared up with exclamation mark", "🆙"},
	{"squared vs", "🆚"},
	{"squared katakana koko", "🈁"},
	{"squared katakana sa", "🈂"},
	{"squared cjk unified ideograph-7121", "🈚"},
	{"squared cjk unified ideograph-6307", "🈯"},
	{"squared cjk unified ideograph-7981", "🈲"},
	{"squared cjk unified ideograph-7a7a", "🈳"},
	{"squared cjk unified ideograph-5408", "🈴"},
	{"squared cjk unified ideograph-6e80", "🈵"},
	{"squared cjk unified ideograph-6709", "🈶"},
	{"squared cjk unified ideograph-6708", "🈷"},
	{"squared cjk unified ideograph-7533", "🈸"},
	{"squared cjk unified ideograph-5272", "🈹"},
	{"squared cjk unified ideograph-55b6", "🈺"},
	{"circled ideograph advantage", "🉐"},
	{"circled ideograph accept", "🉑"},
	{"cyclone", "🌀"},
	{"foggy", "🌁"},
	{"closed umbrella", "🌂"},
	{"night with stars", "🌃"},
	{"sunrise over mountains", "🌄"},
	{"sunrise", "🌅"},
	{"cityscape at dusk", "🌆"},
	{"sunset over buildings", "🌇"},
	{"rainbow", "🌈"},
	{"bridge at night", "🌉"},
	{"water wave", "🌊"},
	{"volcano", "🌋"},
	{"milky way", "🌌"},
	{"earth globe europe-africa", "🌍"},
	{"earth globe americas", "🌎"},
	{"earth globe asia-australia", "🌏"},
	{"globe with meridians", "🌐"},
	{"new moon symbol", "🌑"},
	{"waxing crescent moon symbol", "🌒"},
	{"first quarter moon symbol", "🌓"},
	{"waxing gibbous moon symbol", "🌔"},
	{"full moon symbol", "🌕"},
	{"waning gibbous moon symbol", "🌖"},
	{"last quarter moon symbol", "🌗"},
	{"waning crescent moon symbol", "🌘"},
	{"crescent moon", "🌙"},
	{"new moon with face", "🌚"},
	{"first quarter moon with face", "🌛"},
	{"last quarter moon with face", "🌜"},
	{"full moon with face", "🌝"},
	{"sun with face", "🌞"},
	{"glowing star", "🌟"},
	{"shooting star", "🌠"},
	{"thermometer", "🌡"},
	{"white sun with small cloud", "🌤"},
	{"white sun behind cloud", "🌥"},
	{"white sun behind cloud with rain", "🌦"},
	{"cloud with rain", "🌧"},
	{"cloud with snow", "🌨"},
	{"cloud with lightning", "🌩"},
	{"cloud with tornado", "🌪"},
	{"fog", "🌫"},
	{"wind blowing face", "🌬"},
	{"hot dog", "🌭"},
	{"taco", "🌮"},
	{"burrito", "🌯"},
	{"chestnut", "🌰"},
	{"seedling", "🌱"},
	{"evergreen tree", "🌲"},
	{"deciduous tree", "🌳"},
	{"palm tree", "🌴"},
	{"cactus", "🌵"},
	{"hot pepper", "🌶"},
	{"tulip", "🌷"},
	{"cherry blossom", "🌸"},
	{"rose", "🌹"},
	{"hibiscus", "🌺"},
	{"sunflower", "🌻"},
	{"blossom", "🌼"},
	{"ear of maize", "🌽"},
	{"ear of rice", "🌾"},
	{"herb", "🌿"},
	{"four leaf clover", "🍀"},
	{"maple leaf", "🍁"},
	{"fallen leaf", "🍂"},
	{"leaf fluttering in wind", "🍃"},
	{"mushroom", "🍄"},
	{"tomato", "🍅"},
	{"aubergine", "🍆"},
	{"grapes", "🍇"},
	{"melon", "🍈"},
	{"watermelon", "🍉"},
	{"tangerine", "🍊"},
	{"lemon", "🍋"},
	{"banana", "🍌"},
	{"pineapple", "🍍"},
	{"red apple", "🍎"},
	{"green apple", "🍏"},
	{"pear", "🍐"},
	{"peach", "🍑"},
	{"cherries", "🍒"},
	{"strawberry", "🍓"},
	{"hamburger", "🍔"},
	{"slice of pizza", "🍕"},
	{"meat on bone", "🍖"},
	{"poultry leg", "🍗"},
	{"rice cracker", "🍘"},
	{"rice ball", "🍙"},
	{"cooked rice", "🍚"},
	{"curry and rice", "🍛"},
	{"steaming bowl", "🍜"},
	{"spaghetti", "🍝"},
	{"bread", "🍞"},
	{"french fries", "🍟"},
	{"roasted sweet potato", "🍠"},
	{"dango", "🍡"},
	{"oden", "🍢"},
	{"sushi", "🍣"},
	{"fried shrimp", "🍤"},
	{"fish cake with swirl design", "🍥"},
	{"soft ice cream", "🍦"},
	{"shaved ice", "🍧"},
	{"ice cream", "🍨"},
	{"doughnut", "🍩"},
	{"cookie", "🍪"},
	{"chocolate bar", "🍫"},
	{"candy", "🍬"},
	{"lollipop", "🍭"},
	{"custard", "🍮"},
	{"honey pot", "🍯"},
	{"shortcake", "🍰"},
	{"bento box", "🍱"},
	{"pot of food", "🍲"},
	{"cooking", "🍳"},
	{"fork and knife", "🍴"},
	{"teacup without handle", "🍵"},
	{"sake bottle and cup", "🍶"},
	{"wine glass", "🍷"},
	{"cocktail glass", "🍸"},
	{"tropical drink", "🍹"},
	{"beer mug", "🍺"},
	{"clinking beer mugs", "🍻"},
	{"baby bottle", "🍼"},
	{"fork and knife with plate", "🍽"},
	{"bottle with popping cork", "🍾"},
	{"popcorn", "🍿"},
	{"ribbon", "🎀"},
	{"wrapped present", "🎁"},
	{"birthday cake", "🎂"},
	{"jack-o-lantern", "🎃"},
	{"christmas tree", "🎄"},
	{"father christmas", "🎅"},
	{"fireworks", "🎆"},
	{"firework sparkler", "🎇"},
	{"balloon", "🎈"},
	{"party popper", "🎉"},
	{"confetti ball", "🎊"},
	{"tanabata tree", "🎋"},
	{"crossed flags", "🎌"},
	{"pine decoration", "🎍"},
	{"japanese dolls", "🎎"},
	{"carp streamer", "🎏"},
	{"wind chime", "🎐"},
	{"moon viewing ceremony", "🎑"},
	{"school satchel", "🎒"},
	{"graduation cap", "🎓"},
	{"military medal", "🎖"},
	{"reminder ribbon", "🎗"},
	{"studio microphone", "🎙"},
	{"level slider", "🎚"},
	{"control knobs", "🎛"},
	{"film frames", "🎞"},
	{"admission tickets", "🎟"},
	{"carousel horse", "🎠"},
	{"ferris wheel", "🎡"},
	{"roller coaster", "🎢"},
	{"fishing pole and fish", "🎣"},
	{"microphone", "🎤"},
	{"movie camera", "🎥"},
	{"cinema", "🎦"},
	{"headphone", "🎧"},
	{"artist palette", "🎨"},
	{"top hat", "🎩"},
	{"circus tent", "🎪"},
	{"ticket", "🎫"},
	{"clapper board", "🎬"},
	{"performing arts", "🎭"},
	{"video game", "🎮"},
	{"direct hit", "🎯"},
	{"slot machine", "🎰"},
	{"billiards", "🎱"},
	{"game die", "🎲"},
	{"bowling", "🎳"},
	{"flower playing cards", "🎴"},
	{"musical note", "🎵"},
	{"multiple musical notes", "🎶"},
	{"saxophone", "🎷"},
	{"guitar", "🎸"},
	{"musical keyboard", "🎹"},
	{"trumpet", "🎺"},
	{"violin", "🎻"},
	{"musical score", "🎼"},
	{"running shirt with sash", "🎽"},
	{"tennis racquet and ball", "🎾"},
	{"ski and ski boot", "🎿"},
	{"basketball and hoop", "🏀"},
	{"chequered flag", "🏁"},
	{"snowboarder", "🏂"},
	{"runner", "🏃"},
	{"surfer", "🏄"},
	{"sports medal", "🏅"},
	{"trophy", "🏆"},
	{"horse racing", "🏇"},
	{"american football", "🏈"},
	{"rugby football", "🏉"},
	{"swimmer", "🏊"},
	{"weight lifter", "🏋"},
	{"golfer", "🏌"},
	{"racing motorcycle", "🏍"},
	{"racing car", "🏎"},
	{"cricket bat and ball", "🏏"},
	{"volleyball", "🏐"},
	{"field hockey stick and ball", "🏑"},
	{"ice hockey stick and puck", "🏒"},
	{"table tennis paddle and ball", "🏓"},
	{"snow capped mountain", "🏔"},
	{"camping", "🏕"},
	{"beach with umbrella", "🏖"},
	{"building construction", "🏗"},
	{"house buildings", "🏘"},
	{"cityscape", "🏙"},
	{"derelict house building", "🏚"},
	{"classical building", "🏛"},
	{"desert", "🏜"},
	{"desert island", "🏝"},
	{"national park", "🏞"},
	{"stadium", "🏟"},
	{"house building", "🏠"},
	{"house with garden", "🏡"},
	{"office building", "🏢"},
	{"japanese post office", "🏣"},
	{"european post office", "🏤"},
	{"hospital", "🏥"},
	{"bank", "🏦"},
	{"automated teller machine", "🏧"},
	{"hotel", "🏨"},
	{"love hotel", "🏩"},
	{"convenience store", "🏪"},
	{"school", "🏫"},
	{"department store", "🏬"},
	{"factory", "🏭"},
	{"izakaya lantern", "🏮"},
	{"japanese castle", "🏯"},
	{"european castle", "🏰"},
	{"waving white flag", "🏳"},
	{"waving black flag", "🏴"},
	{"rosette", "🏵"},
	{"label", "🏷"},
	{"badminton racquet and shuttlecock", "🏸"},
	{"bow and arrow", "🏹"},
	{"amphora", "🏺"},
	{"emoji modifier fitzpatrick type-1-2", "🏻"},
	{"emoji modifier fitzpatrick type-3", "🏼"},
	{"emoji modifier fitzpatrick type-4", "🏽"},
	{"emoji modifier fitzpatrick type-5", "🏾"},
	{"emoji modifier fitzpatrick type-6", "🏿"},
	{"rat", "🐀"},
	{"mouse", "🐁"},
	{"ox", "🐂"},
	{"water buffalo", "🐃"},
	{"cow", "🐄"},
	{"tiger", "🐅"},
	{"leopard", "🐆"},
	{"rabbit", "🐇"},
	{"cat", "🐈"},
	{"dragon", "🐉"},
	{"crocodile", "🐊"},
	{"whale", "🐋"},
	{"snail", "🐌"},
	{"snake", "🐍"},
	{"horse", "🐎"},
	{"ram", "🐏"},
	{"goat", "🐐"},
	{"sheep", "🐑"},
	{"monkey", "🐒"},
	{"rooster", "🐓"},
	{"chicken", "🐔"},
	{"dog", "🐕"},
	{"pig", "🐖"},
	{"boar", "🐗"},
	{"elephant", "🐘"},
	{"octopus", "🐙"},
	{"spiral shell", "🐚"},
	{"bug", "🐛"},
	{"ant", "🐜"},
	{"honeybee", "🐝"},
	{"lady beetle", "🐞"},
	{"fish", "🐟"},
	{"tropical fish", "🐠"},
	{"blowfish", "🐡"},
	{"turtle", "🐢"},
	{"hatching chick", "🐣"},
	{"baby chick", "🐤"},
	{"front-facing baby chick", "🐥"},
	{"bird", "🐦"},
	{"penguin", "🐧"},
	{"koala", "🐨"},
	{"poodle", "🐩"},
	{"dromedary camel", "🐪"},
	{"bactrian camel", "🐫"},
	{"dolphin", "🐬"},
	{"mouse face", "🐭"},
	{"cow face", "🐮"},
	{"tiger face", "🐯"},
	{"rabbit face", "🐰"},
	{"cat face", "🐱"},
	{"dragon face", "🐲"},
	{"spouting whale", "🐳"},
	{"horse face", "🐴"},
	{"monkey face", "🐵"},
	{"dog face", "🐶"},
	{"pig face", "🐷"},
	{"frog face", "🐸"},
	{"hamster face", "🐹"},
	{"wolf face", "🐺"},
	{"bear face", "🐻"},
	{"panda face", "🐼"},
	{"pig nose", "🐽"},
	{"paw prints", "🐾"},
	{"chipmunk", "🐿"},
	{"eyes", "👀"},
	{"eye", "👁"},
	{"ear", "👂"},
	{"nose", "👃"},
	{"mouth", "👄"},
	{"tongue", "👅"},
	{"white up pointing backhand index", "👆"},
	{"white down pointing backhand index", "👇"},
	{"white left pointing backhand index", "👈"},
	{"white right pointing backhand index", "👉"},
	{"fisted hand sign", "👊"},
	{"waving hand sign", "👋"},
	{"ok hand sign", "👌"},
	{"thumbs up sign", "👍"},
	{"thumbs down sign", "👎"},
	{"clapping hands sign", "👏"},
	{"open hands sign", "👐"},
	{"crown", "👑"},
	{"womans hat", "👒"},
	{"eyeglasses", "👓"},
	{"necktie", "👔"},
	{"t-shirt", "👕"},
	{"jeans", "👖"},
	{"dress", "👗"},
	{"kimono", "👘"},
	{"bikini", "👙"},
	{"womans clothes", "👚"},
	{"purse", "👛"},
	{"handbag", "👜"},
	{"pouch", "👝"},
	{"mans shoe", "👞"},
	{"athletic shoe", "👟"},
	{"high-heeled shoe", "👠"},
	{"womans sandal", "👡"},
	{"womans boots", "👢"},
	{"footprints", "👣"},
	{"bust in silhouette", "👤"},
	{"busts in silhouette", "👥"},
	{"boy", "👦"},
	{"girl", "👧"},
	{"man", "👨"},
	{"woman", "👩"},
	{"family", "👪"},
	{"man and woman holding hands", "👫"},
	{"two men holding hands", "👬"},
	{"two women holding hands", "👭"},
	{"police officer", "👮"},
	{"woman with bunny ears", "👯"},
	{"bride with veil", "👰"},
	{"person with blond hair", "👱"},
	{"man with gua pi mao", "👲"},
	{"man with turban", "👳"},
	{"older man", "👴"},
	{"older woman", "👵"},
	{"baby", "👶"},
	{"construction worker", "👷"},
	{"princess", "👸"},
	{"japanese ogre", "👹"},
	{"japanese goblin", "👺"},
	{"ghost", "👻"},
	{"baby angel", "👼"},
	{"extraterrestrial alien", "👽"},
	{"alien monster", "👾"},
	{"imp", "👿"},
	{"skull", "💀"},
	{"information desk person", "💁"},
	{"guardsman", "💂"},
	{"dancer", "💃"},
	{"lipstick", "💄"},
	{"nail polish", "💅"},
	{"face massage", "💆"},
	{"haircut", "💇"},
	{"barber pole", "💈"},
	{"syringe", "💉"},
	{"pill", "💊"},
	{"kiss mark", "💋"},
	{"love letter", "💌"},
	{"ring", "💍"},
	{"gem stone", "💎"},
	{"kiss", "💏"},
	{"bouquet", "💐"},
	{"couple with heart", "💑"},
	{"wedding", "💒"},
	{"beating heart", "💓"},
	{"broken heart", "💔"},
	{"two hearts", "💕"},
	{"sparkling heart", "💖"},
	{"growing heart", "💗"},
	{"heart with arrow", "💘"},
	{"blue heart", "💙"},
	{"green heart", "💚"},
	{"yellow heart", "💛"},
	{"purple heart", "💜"},
	{"heart with ribbon", "💝"},
	{"revolving hearts", "💞"},
	{"heart decoration", "💟"},
	{"diamond shape with a dot inside", "💠"},
	{"electric light bulb", "💡"},
	{"anger symbol", "💢"},
	{"bomb", "💣"},
	{"sleeping symbol", "💤"},
	{"collision symbol", "💥"},
	{"splashing sweat symbol", "💦"},
	{"droplet", "💧"},
	{"dash symbol", "💨"},
	{"pile of poo", "💩"},
	{"flexed biceps", "💪"},
	{"dizzy symbol", "💫"},
	{"speech balloon", "💬"},
	{"thought balloon", "💭"},
	{"white flower", "💮"},
	{"hundred points symbol", "💯"},
	{"money bag", "💰"},
	{"currency exchange", "💱"},
	{"heavy dollar sign", "💲"},
	{"credit card", "💳"},
	{"banknote with yen sign", "💴"},
	{"banknote with dollar sign", "💵"},
	{"banknote with euro sign", "💶"},
	{"banknote with pound sign", "💷"},
	{"money with wings", "💸"},
	{"chart with upwards trend and yen sign", "💹"},
	{"seat", "💺"},
	{"personal computer", "💻"},
	{"briefcase", "💼"},
	{"minidisc", "💽"},
	{"floppy disk", "💾"},
	{"optical disc", "💿"},
	{"dvd", "📀"},
	{"file folder", "📁"},
	{"open file folder", "📂"},
	{"page with curl", "📃"},
	{"page facing up", "📄"},
	{"calendar", "📅"},
	{"tear-off calendar", "📆"},
	{"card index", "📇"},
	{"chart with upwards trend", "📈"},
	{"chart with downwards trend", "📉"},
	{"bar chart", "📊"},
	{"clipboard", "📋"},
	{"pushpin", "📌"},
	{"round pushpin", "📍"},
	{"paperclip", "📎"},
	{"straight ruler", "📏"},
	{"triangular ruler", "📐"},
	{"bookmark tabs", "📑"},
	{"ledger", "📒"},
	{"notebook", "📓"},
	{"notebook with decorative cover", "📔"},
	{"closed book", "📕"},
	{"open book", "📖"},
	{"green book", "📗"},
	{"blue book", "📘"},
	{"orange book", "📙"},
	{"books", "📚"},
	{"name badge", "📛"},
	{"scroll", "📜"},
	{"memo", "📝"},
	{"telephone receiver", "📞"},
	{"pager", "📟"},
	{"fax machine", "📠"},
	{"satellite antenna", "📡"},
	{"public address loudspeaker", "📢"},
	{"cheering megaphone", "📣"},
	{"outbox tray", "📤"},
	{"inbox tray", "📥"},
	{"package", "📦"},
	{"e-mail symbol", "📧"},
	{"incoming envelope", "📨"},
	{"envelope with downwards arrow above", "📩"},
	{"closed mailbox with lowered flag", "📪"},
	{"closed mailbox with raised flag", "📫"},
	{"open mailbox with raised flag", "📬"},
	{"open mailbox with lowered flag", "📭"},
	{"postbox", "📮"},
	{"postal horn", "📯"},
	{"newspaper", "📰"},
	{"mobile phone", "📱"},
	{"mobile phone with rightwards arrow at left", "📲"},
	{"vibration mode", "📳"},
	{"mobile phone off", "📴"},
	{"no mobile phones", "📵"},
	{"antenna with bars", "📶"},
	{"camera", "📷"},
	{"camera with flash", "📸"},
	{"video camera", "📹"},
	{"television", "📺"},
	{"radio", "📻"},
	{"videocassette", "📼"},
	{"film projector", "📽"},
	{"prayer beads", "📿"},
	{"twisted rightwards arrows", "🔀"},
	{"clockwise rightwards and leftwards open circle arrows", "🔁"},
	{"clockwise rightwards and leftwards open circle arrows with circled one overlay", "🔂"},
	{"clockwise downwards and upwards open circle arrows", "🔃"},
	{"anticlockwise downwards and upwards open circle arrows", "🔄"},
	{"low brightness symbol", "🔅"},
	{"high brightness symbol", "🔆"},
	{"speaker with cancellation stroke", "🔇"},
	{"speaker", "🔈"},
	{"speaker with one sound wave", "🔉"},
	{"speaker with three sound waves", "🔊"},
	{"battery", "🔋"},
	{"electric plug", "🔌"},
	{"left-pointing magnifying glass", "🔍"},
	{"right-pointing magnifying glass", "🔎"},
	{"lock with ink pen", "🔏"},
	{"closed lock with key", "🔐"},
	{"key", "🔑"},
	{"lock", "🔒"},
	{"open lock", "🔓"},
	{"bell", "🔔"},
	{"bell with cancellation stroke", "🔕"},
	{"bookmark", "🔖"},
	{"link symbol", "🔗"},
	{"radio button", "🔘"},
	{"back with leftwards arrow above", "🔙"},
	{"end with leftwards arrow above", "🔚"},
	{"on with exclamation mark with left right arrow above", "🔛"},
	{"soon with rightwards arrow above", "🔜"},
	{"top with upwards arrow above", "🔝"},
	{"no one under eighteen symbol", "🔞"},
	{"keycap ten", "🔟"},
	{"input symbol for latin capital letters", "🔠"},
	{"input symbol for latin small letters", "🔡"},
	{"input symbol for numbers", "🔢"},
	{"input symbol for symbols", "🔣"},
	{"input symbol for latin letters", "🔤"},
	{"fire", "🔥"},
	{"electric torch", "🔦"},
	{"wrench", "🔧"},
	{"hammer", "🔨"},
	{"nut and bolt", "🔩"},
	{"hocho", "🔪"},
	{"pistol", "🔫"},
	{"microscope", "🔬"},
	{"telescope", "🔭"},
	{"crystal ball", "🔮"},
	{"six pointed star with middle dot", "🔯"},
	{"japanese symbol for beginner", "🔰"},
	{"trident emblem", "🔱"},
	{"black square button", "🔲"},
	{"white square button", "🔳"},
	{"large red circle", "🔴"},
	{"large blue circle", "🔵"},
	{"large orange diamond", "🔶"},
	{"large blue diamond", "🔷"},
	{"small orange diamond", "🔸"},
	{"small blue diamond", "🔹"},
	{"up-pointing red triangle", "🔺"},
	{"down-pointing red triangle", "🔻"},
	{"up-pointing small red triangle", "🔼"},
	{"down-pointing small red triangle", "🔽"},
	{"om symbol", "🕉"},
	{"dove of peace", "🕊"},
	{"kaaba", "🕋"},
	{"mosque", "🕌"},
	{"synagogue", "🕍"},
	{"menorah with nine branches", "🕎"},
	{"clock face one oclock", "🕐"},
	{"clock face two oclock", "🕑"},
	{"clock face three oclock", "🕒"},
	{"clock face four oclock", "🕓"},
	{"clock face five oclock", "🕔"},
	{"clock face six oclock", "🕕"},
	{"clock face seven oclock", "🕖"},
	{"clock face eight oclock", "🕗"},
	{"clock face nine oclock", "🕘"},
	{"clock face ten oclock", "🕙"},
	{"clock face eleven oclock", "🕚"},
	{"clock face twelve oclock", "🕛"},
	{"clock face one-thirty", "🕜"},
	{"clock face two-thirty", "🕝"},
	{"clock face three-thirty", "🕞"},
	{"clock face four-thirty", "🕟"},
	{"clock face five-thirty", "🕠"},
	{"clock face six-thirty", "🕡"},
	{"clock face seven-thirty", "🕢"},
	{"clock face eight-thirty", "🕣"},
	{"clock face nine-thirty", "🕤"},
	{"clock face ten-thirty", "🕥"},
	{"clock face eleven-thirty", "🕦"},
	{"clock face twelve-thirty", "🕧"},
	{"candle", "🕯"},
	{"mantelpiece clock", "🕰"},
	{"hole", "🕳"},
	{"man in business suit levitating", "🕴"},
	{"sleuth or spy", "🕵"},
	{"dark sunglasses", "🕶"},
	{"spider", "🕷"},
	{"spider web", "🕸"},
	{"joystick", "🕹"},
	{"linked paperclips", "🖇"},
	{"lower left ballpoint pen", "🖊"},
	{"lower left fountain pen", "🖋"},
	{"lower left paintbrush", "🖌"},
	{"lower left crayon", "🖍"},
	{"raised hand with fingers splayed", "🖐"},
	{"reversed hand with middle finger extended", "🖕"},
	{"raised hand with part between middle and ring fingers", "🖖"},
	{"desktop computer", "🖥"},
	{"printer", "🖨"},
	{"three button mouse", "🖱"},
	{"trackball", "🖲"},
	{"frame with picture", "🖼"},
	{"card index dividers", "🗂"},
	{"card file box", "🗃"},
	{"file cabinet", "🗄"},
	{"wastebasket", "🗑"},
	{"spiral note pad", "🗒"},
	{"spiral calendar pad", "🗓"},
	{"compression", "🗜"},
	{"old key", "🗝"},
	{"rolled-up newspaper", "🗞"},
	{"dagger knife", "🗡"},
	{"speaking head in silhouette", "🗣"},
	{"right anger bubble", "🗯"},
	{"ballot box with ballot", "🗳"},
	{"world map", "🗺"},
	{"mount fuji", "🗻"},
	{"tokyo tower", "🗼"},
	{"statue of liberty", "🗽"},
	{"silhouette of japan", "🗾"},
	{"moyai", "🗿"},
	{"grinning face", "😀"},
	{"grinning face with smiling eyes", "😁"},
	{"face with tears of joy", "😂"},
	{"smiling face with open mouth", "😃"},
	{"smiling face with open mouth and smiling eyes", "😄"},
	{"smiling face with open mouth and cold sweat", "😅"},
	{"smiling face with open mouth and tightly-closed eyes", "😆"},
	{"smiling face with halo", "😇"},
	{"smiling face with horns", "😈"},
	{"winking face", "😉"},
	{"smiling face with smiling eyes", "😊"},
	{"face savouring delicious food", "😋"},
	{"relieved face", "😌"},
	{"smiling face with heart-shaped eyes", "😍"},
	{"smiling face with sunglasses", "😎"},
	{"smirking face", "😏"},
	{"neutral face", "😐"},
	{"expressionless face", "😑"},
	{"unamused face", "😒"},
	{"face with cold sweat", "😓"},
	{"pensive face", "😔"},
	{"confused face", "😕"},
	{"confounded face", "😖"},
	{"kissing face", "😗"},
	{"face throwing a kiss", "😘"},
	{"kissing face with smiling eyes", "😙"},
	{"kissing face with closed eyes", "😚"},
	{"face with stuck-out tongue", "😛"},
	{"face with stuck-out tongue and winking eye", "😜"},
	{"face with stuck-out tongue and tightly-closed eyes", "😝"},
	{"disappointed face", "😞"},
	{"worried face", "😟"},
	{"angry face", "😠"},
	{"pouting face", "😡"},
	{"crying face", "😢"},
	{"persevering face", "😣"},
	{"face with look of triumph", "😤"},
	{"disappointed but relieved face", "😥"},
	{"frowning face with open mouth", "😦"},
	{"anguished face", "😧"},
	{"fearful face", "😨"},
	{"weary face", "😩"},
	{"sleepy face", "😪"},
	{"tired face", "😫"},
	{"grimacing face", "😬"},
	{"loudly crying face", "😭"},
	{"face with open mouth", "😮"},
	{"hushed face", "😯"},
	{"face with open mouth and cold sweat", "😰"},
	{"face screaming in fear", "😱"},
	{"astonished face", "😲"},
	{"flushed face", "😳"},
	{"sleeping face", "😴"},
	{"dizzy face", "😵"},
	{"face without mouth", "😶"},
	{"face with medical mask", "😷"},
	{"grinning cat face with smiling eyes", "😸"},
	{"cat face with tears of joy", "😹"},
	{"smiling cat face with open mouth", "😺"},
	{"smiling cat face with heart-shaped eyes", "😻"},
	{"cat face with wry smile", "😼"},
	{"kissing cat face with closed eyes", "😽"},
	{"pouting cat face", "😾"},
	{"crying cat face", "😿"},
	{"weary cat face", "🙀"},
	{"slightly frowning face", "🙁"},
	{"slightly smiling face", "🙂"},
	{"upside-down face", "🙃"},
	{"face with rolling eyes", "🙄"},
	{"face with no good gesture", "🙅"},
	{"face with ok gesture", "🙆"},
	{"person bowing deeply", "🙇"},
	{"see-no-evil monkey", "🙈"},
	{"hear-no-evil monkey", "🙉"},
	{"speak-no-evil monkey", "🙊"},
	{"happy person raising one hand", "🙋"},
	{"person raising both hands in celebration", "🙌"},
	{"person frowning", "🙍"},
	{"person with pouting face", "🙎"},
	{"person with folded hands", "🙏"},
	{"rocket", "🚀"},
	{"helicopter", "🚁"},
	{"steam locomotive", "🚂"},
	{"railway car", "🚃"},
	{"high-speed train", "🚄"},
	{"high-speed train with bullet nose", "🚅"},
	{"train", "🚆"},
	{"metro", "🚇"},
	{"light rail", "🚈"},
	{"station", "🚉"},
	{"tram", "🚊"},
	{"tram car", "🚋"},
	{"bus", "🚌"},
	{"oncoming bus", "🚍"},
	{"trolleybus", "🚎"},
	{"bus stop", "🚏"},
	{"minibus", "🚐"},
	{"ambulance", "🚑"},
	{"fire engine", "🚒"},
	{"police car", "🚓"},
	{"oncoming police car", "🚔"},
	{"taxi", "🚕"},
	{"oncoming taxi", "🚖"},
	{"automobile", "🚗"},
	{"oncoming automobile", "🚘"},
	{"recreational vehicle", "🚙"},
	{"delivery truck", "🚚"},
	{"articulated lorry", "🚛"},
	{"tractor", "🚜"},
	{"monorail", "🚝"},
	{"mountain railway", "🚞"},
	{"suspension railway", "🚟"},
	{"mountain cableway", "🚠"},
	{"aerial tramway", "🚡"},
	{"ship", "🚢"},
	{"rowboat", "🚣"},
	{"speedboat", "🚤"},
	{"horizontal traffic light", "🚥"},
	{"vertical traffic light", "🚦"},
	{"construction sign", "🚧"},
	{"police cars revolving light", "🚨"},
	{"triangular flag on post", "🚩"},
	{"door", "🚪"},
	{"no entry sign", "🚫"},
	{"smoking symbol", "🚬"},
	{"no smoking symbol", "🚭"},
	{"put litter in its place symbol", "🚮"},
	{"do not litter symbol", "🚯"},
	{"potable water symbol", "🚰"},
	{"non-potable water symbol", "🚱"},
	{"bicycle", "🚲"},
	{"no bicycles", "🚳"},
	{"bicyclist", "🚴"},
	{"mountain bicyclist", "🚵"},
	{"pedestrian", "🚶"},
	{"no pedestrians", "🚷"},
	{"children crossing", "🚸"},
	{"mens symbol", "🚹"},
	{"womens symbol", "🚺"},
	{"restroom", "🚻"},
	{"baby symbol", "🚼"},
	{"toilet", "🚽"},
	{"water closet", "🚾"},
	{"shower", "🚿"},
	{"bath", "🛀"},
	{"bathtub", "🛁"},
	{"passport control", "🛂"},
	{"customs", "🛃"},
	{"baggage claim", "🛄"},
	{"left luggage", "🛅"},
	{"couch and lamp", "🛋"},
	{"sleeping accommodation", "🛌"},
	{"shopping bags", "🛍"},
	{"bellhop bell", "🛎"},
	{"bed", "🛏"},
	{"place of worship", "🛐"},
	{"hammer and wrench", "🛠"},
	{"shield", "🛡"},
	{"oil drum", "🛢"},
	{"motorway", "🛣"},
	{"railway track", "🛤"},
	{"motor boat", "🛥"},
	{"small airplane", "🛩"},
	{"airplane departure", "🛫"},
	{"airplane arriving", "🛬"},
	{"satellite", "🛰"},
	{"passenger ship", "🛳"},
	{"zipper-mouth face", "🤐"},
	{"money-mouth face", "🤑"},
	{"face with thermometer", "🤒"},
	{"nerd face", "🤓"},
	{"thinking face", "🤔"},
	{"face with head-bandage", "🤕"},
	{"robot face", "🤖"},
	{"hugging face", "🤗"},
	{"sign of the horns", "🤘"},
	{"crab", "🦀"},
	{"lion face", "🦁"},
	{"scorpion", "🦂"},
	{"turkey", "🦃"},
	{"unicorn face", "🦄"},
	{"cheese wedge", "🧀"},
	{"keycap number sign", "#"},
	{"keycap asterisk", "*"},
	{"keycap digit zero", "0"},
	{"keycap digit one", "1"},
	{"keycap digit two", "2"},
	{"keycap digit three", "3"},
	{"keycap digit four", "4"},
	{"keycap digit five", "5"},
	{"keycap digit six", "6"},
	{"keycap digit seven", "7"},
	{"keycap digit eight", "8"},
	{"keycap digit nine", "9"},
	{"flag for ascension island", "🇦"},
	{"flag for andorra", "🇦"},
	{"flag for united arab emirates", "🇦"},
	{"flag for afghanistan", "🇦"},
	{"flag for antigua & barbuda", "🇦"},
	{"flag for anguilla", "🇦"},
	{"flag for albania", "🇦"},
	{"flag for armenia", "🇦"},
	{"flag for angola", "🇦"},
	{"flag for antarctica", "🇦"},
	{"flag for argentina", "🇦"},
	{"flag for american samoa", "🇦"},
	{"flag for austria", "🇦"},
	{"flag for australia", "🇦"},
	{"flag for aruba", "🇦"},
	{"flag for åland islands", "🇦"},
	{"flag for azerbaijan", "🇦"},
	{"flag for bosnia & herzegovina", "🇧"},
	{"flag for barbados", "🇧"},
	{"flag for bangladesh", "🇧"},
	{"flag for belgium", "🇧"},
	{"flag for burkina faso", "🇧"},
	{"flag for bulgaria", "🇧"},
	{"flag for bahrain", "🇧"},
	{"flag for burundi", "🇧"},
	{"flag for benin", "🇧"},
	{"flag for st. barthélemy", "🇧"},
	{"flag for bermuda", "🇧"},
	{"flag for brunei", "🇧"},
	{"flag for bolivia", "🇧"},
	{"flag for caribbean netherlands", "🇧"},
	{"flag for brazil", "🇧"},
	{"flag for bahamas", "🇧"},
	{"flag for bhutan", "🇧"},
	{"flag for bouvet island", "🇧"},
	{"flag for botswana", "🇧"},
	{"flag for belarus", "🇧"},
	{"flag for belize", "🇧"},
	{"flag for canada", "🇨"},
	{"flag for cocos islands", "🇨"},
	{"flag for congo - kinshasa", "🇨"},
	{"flag for central african republic", "🇨"},
	{"flag for congo - brazzaville", "🇨"},
	{"flag for switzerland", "🇨"},
	{"flag for côte d’ivoire", "🇨"},
	{"flag for cook islands", "🇨"},
	{"flag for chile", "🇨"},
	{"flag for cameroon", "🇨"},
	{"flag for china", "🇨"},
	{"flag for colombia", "🇨"},
	{"flag for clipperton island", "🇨"},
	{"flag for costa rica", "🇨"},
	{"flag for cuba", "🇨"},
	{"flag for cape verde", "🇨"},
	{"flag for curaçao", "🇨"},
	{"flag for christmas island", "🇨"},
	{"flag for cyprus", "🇨"},
	{"flag for czech republic", "🇨"},
	{"flag for germany", "🇩"},
	{"flag for diego garcia", "🇩"},
	{"flag for djibouti", "🇩"},
	{"flag for denmark", "🇩"},
	{"flag for dominica", "🇩"},
	{"flag for dominican republic", "🇩"},
	{"flag for algeria", "🇩"},
	{"flag for ceuta & melilla", "🇪"},
	{"flag for ecuador", "🇪"},
	{"flag for estonia", "🇪"},
	{"flag for egypt", "🇪"},
	{"flag for western sahara", "🇪"},
	{"flag for eritrea", "🇪"},
	{"flag for spain", "🇪"},
	{"flag for ethiopia", "🇪"},
	{"flag for european union", "🇪"},
	{"flag for finland", "🇫"},
	{"flag for fiji", "🇫"},
	{"flag for falkland islands", "🇫"},
	{"flag for micronesia", "🇫"},
	{"flag for faroe islands", "🇫"},
	{"flag for france", "🇫"},
	{"flag for gabon", "🇬"},
	{"flag for united kingdom", "🇬"},
	{"flag for grenada", "🇬"},
	{"flag for georgia", "🇬"},
	{"flag for french guiana", "🇬"},
	{"flag for guernsey", "🇬"},
	{"flag for ghana", "🇬"},
	{"flag for gibraltar", "🇬"},
	{"flag for greenland", "🇬"},
	{"flag for gambia", "🇬"},
	{"flag for guinea", "🇬"},
	{"flag for guadeloupe", "🇬"},
	{"flag for equatorial guinea", "🇬"},
	{"flag for greece", "🇬"},
	{"flag for south georgia & south sandwich islands", "🇬"},
	{"flag for guatemala", "🇬"},
	{"flag for guam", "🇬"},
	{"flag for guinea-bissau", "🇬"},
	{"flag for guyana", "🇬"},
	{"flag for hong kong", "🇭"},
	{"flag for heard & mcdonald islands", "🇭"},
	{"flag for honduras", "🇭"},
	{"flag for croatia", "🇭"},
	{"flag for haiti", "🇭"},
	{"flag for hungary", "🇭"},
	{"flag for canary islands", "🇮"},
	{"flag for indonesia", "🇮"},
	{"flag for ireland", "🇮"},
	{"flag for israel", "🇮"},
	{"flag for isle of man", "🇮"},
	{"flag for india", "🇮"},
	{"flag for british indian ocean territory", "🇮"},
	{"flag for iraq", "🇮"},
	{"flag for iran", "🇮"},
	{"flag for iceland", "🇮"},
	{"flag for italy", "🇮"},
	{"flag for jersey", "🇯"},
	{"flag for jamaica", "🇯"},
	{"flag for jordan", "🇯"},
	{"flag for japan", "🇯"},
	{"flag for kenya", "🇰"},
	{"flag for kyrgyzstan", "🇰"},
	{"flag for cambodia", "🇰"},
	{"flag for kiribati", "🇰"},
	{"flag for comoros", "🇰"},
	{"flag for st. kitts & nevis", "🇰"},
	{"flag for north korea", "🇰"},
	{"flag for south korea", "🇰"},
	{"flag for kuwait", "🇰"},
	{"flag for cayman islands", "🇰"},
	{"flag for kazakhstan", "🇰"},
	{"flag for laos", "🇱"},
	{"flag for lebanon", "🇱"},
	{"flag for st. lucia", "🇱"},
	{"flag for liechtenstein", "🇱"},
	{"flag for sri lanka", "🇱"},
	{"flag for liberia", "🇱"},
	{"flag for lesotho", "🇱"},
	{"flag for lithuania", "🇱"},
	{"flag for luxembourg", "🇱"},
	{"flag for latvia", "🇱"},
	{"flag for libya", "🇱"},
	{"flag for morocco", "🇲"},
	{"flag for monaco", "🇲"},
	{"flag for moldova", "🇲"},
	{"flag for montenegro", "🇲"},
	{"flag for st. martin", "🇲"},
	{"flag for madagascar", "🇲"},
	{"flag for marshall islands", "🇲"},
	{"flag for macedonia", "🇲"},
	{"flag for mali", "🇲"},
	{"flag for myanmar", "🇲"},
	{"flag for mongolia", "🇲"},
	{"flag for macau", "🇲"},
	{"flag for northern mariana islands", "🇲"},
	{"flag for martinique", "🇲"},
	{"flag for mauritania", "🇲"},
	{"flag for montserrat", "🇲"},
	{"flag for malta", "🇲"},
	{"flag for mauritius", "🇲"},
	{"flag for maldives", "🇲"},
	{"flag for malawi", "🇲"},
	{"flag for mexico", "🇲"},
	{"flag for malaysia", "🇲"},
	{"flag for mozambique", "🇲"},
	{"flag for namibia", "🇳"},
	{"flag for new caledonia", "🇳"},
	{"flag for niger", "🇳"},
	{"flag for norfolk island", "🇳"},
	{"flag for nigeria", "🇳"},
	{"flag for nicaragua", "🇳"},
	{"flag for netherlands", "🇳"},
	{"flag for norway", "🇳"},
	{"flag for nepal", "🇳"},
	{"flag for nauru", "🇳"},
	{"flag for niue", "🇳"},
	{"flag for new zealand", "🇳"},
	{"flag for oman", "🇴"},
	{"flag for panama", "🇵"},
	{"flag for peru", "🇵"},
	{"flag for french polynesia", "🇵"},
	{"flag for papua new guinea", "🇵"},
	{"flag for philippines", "🇵"},
	{"flag for pakistan", "🇵"},
	{"flag for poland", "🇵"},
	{"flag for st. pierre & miquelon", "🇵"},
	{"flag for pitcairn islands", "🇵"},
	{"flag for puerto rico", "🇵"},
	{"flag for palestinian territories", "🇵"},
	{"flag for portugal", "🇵"},
	{"flag for palau", "🇵"},
	{"flag for paraguay", "🇵"},
	{"flag for qatar", "🇶"},
	{"flag for réunion", "🇷"},
	{"flag for romania", "🇷"},
	{"flag for serbia", "🇷"},
	{"flag for russia", "🇷"},
	{"flag for rwanda", "🇷"},
	{"flag for saudi arabia", "🇸"},
	{"flag for solomon islands", "🇸"},
	{"flag for seychelles", "🇸"},
	{"flag for sudan", "🇸"},
	{"flag for sweden", "🇸"},
	{"flag for singapore", "🇸"},
	{"flag for st. helena", "🇸"},
	{"flag for slovenia", "🇸"},
	{"flag for svalbard & jan mayen", "🇸"},
	{"flag for slovakia", "🇸"},
	{"flag for sierra leone", "🇸"},
	{"flag for san marino", "🇸"},
	{"flag for senegal", "🇸"},
	{"flag for somalia", "🇸"},
	{"flag for suriname", "🇸"},
	{"flag for south sudan", "🇸"},
	{"flag for são tomé & príncipe", "🇸"},
	{"flag for el salvador", "🇸"},
	{"flag for sint maarten", "🇸"},
	{"flag for syria", "🇸"},
	{"flag for swaziland", "🇸"},
	{"flag for tristan da cunha", "🇹"},
	{"flag for turks & caicos islands", "🇹"},
	{"flag for chad", "🇹"},
	{"flag for french southern territories", "🇹"},
	{"flag for togo", "🇹"},
	{"flag for thailand", "🇹"},
	{"flag for tajikistan", "🇹"},
	{"flag for tokelau", "🇹"},
	{"flag for timor-leste", "🇹"},
	{"flag for turkmenistan", "🇹"},
	{"flag for tunisia", "🇹"},
	{"flag for tonga", "🇹"},
	{"flag for turkey", "🇹"},
	{"flag for trinidad & tobago", "🇹"},
	{"flag for tuvalu", "🇹"},
	{"flag for taiwan", "🇹"},
	{"flag for tanzania", "🇹"},
	{"flag for ukraine", "🇺"},
	{"flag for uganda", "🇺"},
	{"flag for u.s. outlying islands", "🇺"},
	{"flag for united states", "🇺"},
	{"flag for uruguay", "🇺"},
	{"flag for uzbekistan", "🇺"},
	{"flag for vatican city", "🇻"},
	{"flag for st. vincent & grenadines", "🇻"},
	{"flag for venezuela", "🇻"},
	{"flag for british virgin islands", "🇻"},
	{"flag for u.s. virgin islands", "🇻"},
	{"flag for vietnam", "🇻"},
	{"flag for vanuatu", "🇻"},
	{"flag for wallis & futuna", "🇼"},
	{"flag for samoa", "🇼"},
	{"flag for kosovo", "🇽"},
	{"flag for yemen", "🇾"},
	{"flag for mayotte", "🇾"},
	{"flag for south africa", "🇿"},
	{"flag for zambia", "🇿"},
	{"flag for zimbabwe", "🇿"}
};

// EMOJI ARRAY END

/* =================== UTILITY FUNCTIONS =================== */
void help(){
	printf("emoji v%s\n", VERSION);
	printf("by Japroz Saini<sainijaproz@gmail.com>\n");
	printf("\n");
	printf(
		"Usage :: emoji [emoji_name]\n\n"
		"Options::\n"
		"	--help		Prints this message\n"
		"	--version	Prints version\n\n"
		"License :: MIT\n"
	);
}

void version(){
	printf("emoji v%s\n", VERSION);
}

char* lower(char *str, size_t len){
    char *str_l = calloc(len+1, sizeof(char));

    for (size_t i = 0; i < len; ++i) {
        str_l[i] = tolower((unsigned char)str[i]);
    }
    return str_l;
}

void red_bold() {
  printf("\033[1;31m");
}

void reset () {
  printf("\033[0m");
}
/* =================== UTILITY FUNCTIONS END =================== */

void print_emoji(const char* str){
	bool found = false;
	for(int i = 0;i < emojis_len;i++){
		if(strcmp(str, emojis[i][0]) == 0){
			printf("%s\n", emojis[i][1]);
			found = true;
		}
	}

	if(!found){
		red_bold();
		printf("error:");
		reset();
		printf(" No emoji by the name of \"%s\" was found\n", str);
	}
}

int main(int argc, char** argv){
	int p = 0;
	char str[MAX_BUF];
	if(
	  argc == 1 ||
	  (argc == 2 && (strcmp(argv[1], "--help") == 0)))
	{
		help();
		exit(EXIT_SUCCESS);
	}

	if(
	  (argc == 2 && (strcmp(argv[1], "--version") == 0)) ||
	  (argc == 2 && (strcmp(argv[1], "-V") == 0)))
	{
		version();
		exit(EXIT_SUCCESS);
	}

	for(int i = 1;i < argc;i++){
		for(int j = 0;j < (int)strlen(argv[i]);j++){
			str[p] = argv[i][j];
			p++;
		}
		if(i != (argc - 1)){
			str[p] = ' ';
			p++;
		}
	}

	print_emoji(lower(str, p));

	return EXIT_SUCCESS;
}
